### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by asacavanagh** [robinp7720/MC-CoreProtect-Web-GUI#1]
Hi!

I was just testing out this WebGUI for use with my server, however I'm having a slight issue with getting it to connect to the database. I've checked the credentials several times against multiple other config files from my servers plugins folder but am still unable to get the "Users" tab to work.

Currently, it just displays:
![image](https://cloud.githubusercontent.com/assets/2492964/9429016/6a8a645c-4a05-11e5-8cb0-a662cdb6c8de.png)

I did notice there was an "$interfacepass" in the coreprotect.php config file which is blank, but there is no option for this on the settings page.

Any help would be greatly appreciated :)
Thanks!

**Comment by AngryNoodlez** [comment]
Hi asacavanagh,

Your coreprotect.php file should look something like this;

<?php $host="localhost";$user="CoreProtectUser";$dbpass="CoreProtectPassword";$dbname="coreprotect";$tablepre="co_";$interfacepass="";$con=mysqli_connect($host,$user,$dbpass,$dbname);?>

It has a number of database settings;

$host - Hostname / IP address of the server with the MySQL database on it
$user - Database Username with access to the CoreProtect database
$dbpass - Password for the user account above
$dbname - name of the database on the MySQL server

The error you are receiving is because PHP cannot connect to the MySQL database with the credentials you have supplied. You will need to fill in all of the database settings listed above for it to work.

Let me know how you get on.

~~EDIT - I've just checked, and there is definitely an option for the database password in the Settings page.
Settings -> CoreProtect Database -> Database password

**Comment by asacavanagh** [comment]
Hi

Thanks for getting back to me so promptly.

I have that file filled out fully and everything reflects what is in my coreprotect config file, this is what confuses me about the error appearing when I go to use the site.

Cheers!

**Comment by asacavanagh** [comment]
I can't seem to edit my previous comment, but in regards to your edit:

The coreprotect password wasn't what I meant by not being there. In the config file there is an extra section that isn't listed on the settings page ("$interfacepass"). Not that I could see anyway.

**Comment by AngryNoodlez** [comment]
Hi asacavanagh,

The $interfacepass option is the setting for the password login form to log into the CoreProtect interface. You can find this setting under General Settings.

Did you manage to get it working?

**Comment by asacavanagh** [comment]
Currently, no. I'm not sure what the problem could be then. As far as I can tell, this is all set up correctly but is just being denied login for some reason or other.

**Comment by AngryNoodlez** [comment]
Can you try using your MySQL server root username & password to log into the CoreProtect database? This will help rule out the possibility of incorrect credentials..

Also, is the MySQL server hosted on the same machine as the MineCraft server? Or is it remote?

**Comment by asacavanagh** [comment]
I believe our system admin has our root user for MySQL disabled for security reason, or something along those lines, so I'm using the credentials I was give for use with this particular server's databases.

As I said previously though, what I've put into the coreprotect.php file matches what is in the CoreProtect's config.yml. The server is live, so I know the credentials work.

It is hosted on the same box as the Minecraft servers, yes.

**Comment by AngryNoodlez** [comment]
There's only one of two issues I can really think of that would cause this error;

1 - The MySQL username/password is either incorrect, or doesn't have permission to access the database.
2 - CoreProtect is configured to use a table prefix other than the default '_co'. Can you check if the database prefix is the same as the one specified in the CoreProtect.php file?

~~Edit - Also, is the host specified by IP address or using 'localhost' ?

**Comment by asacavanagh** [comment]
1. I'm positive it does and is correct
2. They both are "coreprotect_"

So I'm stumped as to what the problem is :s

**Comment by AngryNoodlez** [comment]
Can you create a test php file with the code below and see if it connects to the database successfully?

<?php
$link = mysqli_connect('localhost', 'dbuser', 'dbpassword', 'dbname');

if (!$link) {
    die('Connect Error (' . mysqli_connect_errno() . ') ' . mysqli_connect_error());
}

echo 'Connected... ' . mysqli_get_host_info($link) . "\n";
?>

**Comment by asacavanagh** [comment]
Responds with:

![image](https://cloud.githubusercontent.com/assets/2492964/9430860/72ce2180-4a46-11e5-85eb-82259084c6dc.png)

**Comment by asacavanagh** [comment]
Okay... I changed the ownership of the coreprotect.php file and it started working. Interesting,  I wouldn't think that'd of had anything to do with it.

Anyway, thanks for your time and help, it was much appreciated :)
